### ISSUE TITLE
Some minor ui issue in mobile

### ISSUE THREAD

**Issue by akhilmhdh** [tinkerhub/saturday-hack-night#11] opened 2022-10-19 17:25 UTC
Here are some padding issues in mobile screen for saturday hack night that I noticed.

## Missing Padding on both sides

![Screenshot 2022-10-19 at 10 50 25 PM](https://user-images.githubusercontent.com/31166322/196761611-ff3c4b75-deaf-45e9-94f2-8a4be5ca15e6.png)

## Padding made off aligned with other sections in page

![Screenshot 2022-10-19 at 10 50 43 PM](https://user-images.githubusercontent.com/31166322/196761635-c8d96a08-56a3-4a37-aeac-4a96b41849e0.png)

- And also can someone please add a bg for navbar as its crossing with animation

But i must say great job team on this site. Looks awesome

**Comment by DarkPhoenix2704** [comment] 2022-10-19 18:36
- [x] ~Padding Issue in Accordion~ Fixed in 57459efb91eac9009e222b878a829cccc79c3f87
- [x] ~bg for navbar~ Added in  b8847486d792da718d100ed4c70b5db3bd8478f9
- [ ]  Padding issue in some sections

**Comment by DarkPhoenix2704** [comment] 2022-10-19 18:42
> ## Padding made off aligned with other sections in page
> ![Screenshot 2022-10-19 at 10 50 43 PM](https://user-images.githubusercontent.com/31166322/196761635-c8d96a08-56a3-4a37-aeac-4a96b41849e0.png)

Couldn't reproduce the issue. Can you share what browser you are using?

**Comment by akhilmhdh** [comment] 2022-10-22 15:02
Sorry for late reply. Firefox it is

**Comment by DarkPhoenix2704** [comment] 2022-11-19 09:48
I tried multiple versions of Firefox & can't reproduce this issue

**Closed** 2023-01-12 07:37 UTC
Labels: good first issue, wontfix, hacktoberfest
