### ISSUE TITLE
website reloading automaticall every few minutes

### ISSUE THREAD

**Issue by sreehari2003** [tinkerhub/saturday-hack-night#25] opened 2022-11-15 13:50 UTC
## site is automatically reloading every few minutes this is probably due to the caching issue

**Comment by DarkPhoenix2704** [comment] 2022-11-15 13:52
#24 is not merged yet. It also has some issues

**Comment by DarkPhoenix2704** [comment] 2022-11-15 13:53
I'm marking this as duplicate of #22

**Closed by DarkPhoenix2704** 2022-11-15 13:53 UTC
